package webapp.services;

public class CustomerDTO {

	/**
	 * Customer's internal identification (unique, primary key, sequential)
	 * Generated by the database engine.
	 */
	public final int id;

	/**
	 * Customer's VAT number
	 */
	public final int vat;

	/**
	 * Customer's name. In case of a company, the represents its commercial denomination 
	 */
	public final String designation;
	
	/**
	 * Customer's contact number
	 */
	public final int phoneNumber;

	public CustomerDTO(int id, int vat, String designation, int phoneNumber) {
		this.id = id;
		this.vat = vat;
		this.designation = designation;
		this.phoneNumber = phoneNumber;
	}

	public int getId() {
		return this.id;
	}

	public int getVat() {
		return this.vat;
	}

	public String getDesignation() {
		return this.designation;
	}

	public int getPhoneNumber() {
		return this.phoneNumber;
	}
	
}
