package webapp.services;

import java.util.Date;

public class SaleDTO {
	// Sale attributes

	/**
	 * Sale's internal identification (unique, primary key, sequential)
	 * Generated by the database engine.
	 */
	public final int id;

	/**
	 * SAle's date
	 */
	public final Date data;

	/**
	 * Sale's total
	 */
	public final Double total;
	
	/**
	 * Sale's status
	 */
	public final String statusId;
	
	/**
	 * Sale's customer Vat
	 */
	public final int customerVat;
	
	public SaleDTO(int id, Date date, Double total, String statusId, int customerVat) {
		this.id = id;
		this.data = date;
		this.total = 0.0;
		this.statusId = statusId;
		this.customerVat = customerVat;
	}

	public int getId() {
		return this.id;
	}

	public Date getData() {
		return this.data;
	}

	public Double getTotal() {
		return this.total;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public int getCustomerVat() {
		return this.customerVat;
	}
	
	
}
