package webapp.services;

public class SaleDeliveryDTO {
	// Sale attributes

	/**
	 * Sale's internal identification (unique, primary key, sequential)
	 * Generated by the database engine.
	 */
	public final int id;
	
	/**
	 * Sale's delivery id
	 */
	
	public final int sale_id;

	/**
	 * Sale's delivery customer vat
	 */
	
	public final int customer_vat;
	
	/**
	 * Sale's delivery address id
	 */
	
	public final int addr_id;

	public SaleDeliveryDTO(int id, int sale_id, int customer_vat, int addr_id) {
		this.id = id;
		this.addr_id = addr_id;
		this.sale_id = sale_id;
		this.customer_vat = customer_vat;	
	}
}
